schema-version: 1
id: initial-cursor-at-top-or-bottom
name: Initial Cursor At Top Or Bottom
author: Nathanael Nerode
description: This small extension eliminates the three newlines printed before the
  banner.  It also provides a tool to attempt to place the cursor at the bottom of
  the screen, like old Infocom games.  Due to wild variance between interpreters,
  it is not reliable.
