schema-version: 1
id: mille-una-for-gargoyle-with-graphics
name: MilleUna for Gargoyle with graphics
author: Leonardo Boselli
description: '.


  Graphics window position is g-left.

  Graphics window pixel count is 120.

  Graphics background color is '
