schema-version: 1
id: scope-caching
name: Scope Caching
author: Mike Ciul
description: Gives things the 'marked visible' property, to check the visibility of
  something without repeating the entire scope loop each time. Works with Epistemology
  by Eric Eve, Conditional Backdrops by Mike Ciul, and Remembering by Aaron Reed.
