schema-version: 1
id: glimmr-drawing-commands-for-glulx-only
name: Glimmr Drawing Commands (for Glulx only)
author: Erik Temple
description: Provides commands for displaying images, shape primitives (such as rectangles,
  boxes, and lines), user-specified bitmap drawings, image maps, and for text-painting
  using 'fonts' with glyphs composed of either bitmaps or image files.
