schema-version: 1
id: spelling-corrector
name: SpellingCorrector
author: Steve Breslin in collaboration with Andreas Sewe
description: A context-sensitive typo and spelling corrector. Version 1.1, by Steve
  Breslin in collaboration with Andreas Sewe.
