schema-version: 1
id: whowhat-h
name: whowhat.h
author: David Cornelson
description: a library to provide support for input such as "who is..." and "what
  is...". Written by David Cornelson, based on "whatis.h" by A.C. Murie.
