schema-version: 1
id: phrases-for-adaptive-pacing
name: Phrases for Adaptive Pacing
author: Ron Newcomb
description: We may ask the time when (a description of scenes) began/ended; the number
  of turns since (a description of scenes) began/ended; if (a future event) is soon;
  the time/turns until (a future event); the time/turns when (a future event). We
  may also un-schedule a future event with 'never shall'; begin or end a scene on
  an event; say a time 'as a time period'; repeat through future events; and change
  the turns-to-minutes ratio with 'per'.
