schema-version: 1
id: underside
name: Underside
author: Eric Eve
description: Allows objects to be put under other objects. An underside usually starts
  out closed so that its contents are hidden from view. Requires Version 7 (or later)
  of Bulk Limiter; the space under objects is limited by bulk. Underside is compatible
  with Version 10 or later of Implicit Actions, but does not require it. Version 5
  of Underside avoids features deprecated in Version 6E59 of Inform.
