schema-version: 1
id: story-mode
name: Story Mode
author: Drew Cook
description: Provides an optional mode in which the game automatically steps through
  a walkthrough. At any time, players can pause the guide and play independently.
  At any future point, players can return to the walkthrough in progress. This is
  a 'safe' mode of play in which neither the walkthrough nor the game world can be
  disrupted. The primary design goal of story mode is improved accessibility, though
  it has potential as a tutorial feature.
