schema-version: 1
id: simple-followers-it
name: Simple Followers IT
author: Leonardo Boselli
description: Allows non-player characters to follow the player (or one another); adds
  a FOLLOW command and a corresponding STOP FOLLOWING command so that the player can
  issue these orders to non-player characters. Semplicemente tradotto in italiano.
