schema-version: 1
id: recorded-endings-for-glulx-only
name: Recorded Endings (for Glulx only)
author: Emily Short
description: Records the endings the player encounters in multiple play-throughs to
  an external file; then adds an ENDINGS option to the final question to allow the
  player to review which endings he has seen so far.
