schema-version: 1
id: permission-to-visit
name: Permission To Visit
author: Ron Newcomb
description: In lieu of compass directions, we may VISIT, ATTEND, GO TO, and FIND
  various people, events, places, and things.  Characters may INVITE, PERMIT, and
  FORBID each other to or from their respective domains.
