schema-version: 1
id: hypothetical-questions
name: Hypothetical Questions
author: Tara McGrew
description: Allows us to test the consequences of a phrase or action without permanently
  changing the game state.
